Repository TYPO3-Documentation/TYPO3CMS-Reference-TCA, pull requests merged in 2022-05, with the labels that each got.

#591 Hint at TSConfig
  Documentation/Columns/Properties/Label.rst
Labels: backport 11.5

#595 [TASK] Add example to linkPopup fieldControl documentation
  Documentation/ColumnsConfig/Type/Input/Properties/LinkPopup.rst
Labels: backport 10.4

#597 Fix inconsistent indents
  Documentation/ColumnsConfig/Type/Flex/FlexformSyntax.rst
Labels: backport 11.5, backport 10.4
