Repository TYPO3-Documentation/TYPO3CMS-Reference-TCA, pull requests merged in 2022-04, with the labels that each got.

#577 [TASK] Move Checkbox examples to the main checkbox page
  Documentation/ColumnsConfig/Type/Check/Default.rst
  Documentation/ColumnsConfig/Type/Check/Examples/DefaultExamples.rst
  Documentation/ColumnsConfig/Type/Check/Examples/LabeledToggleExamples.rst
  Documentation/ColumnsConfig/Type/Check/Examples/ToggleExample.rst
  Documentation/ColumnsConfig/Type/Check/LabeledToggle.rst
  Documentation/ColumnsConfig/Type/Check/Toggle.rst
Labels: backport 11.5

#582 [TASK] Document fileByUrlAllowed
  Documentation/ColumnsConfig/Type/Inline/Properties/Appearance.rst
Labels: backport 11.5, backport 10.4

#585 [TASK] Remove unavailable "spec" linkHandler
  Documentation/ColumnsConfig/Type/Input/Properties/LinkPopup.rst
Labels: backport 10.4

#588 [TASK] Remove templating tutorial from Settings.cfg
  Documentation/Settings.cfg
Labels: backport 11.5, backport 10.4
