Repository TYPO3-Documentation/TYPO3CMS-Reference-TCA, pull requests merged in 2023-12, with the labels that each got.

#882 [TASK] Adjust deprecation of TCA type "input"
  Documentation/ColumnsConfig/Type/Input/Index.rst
Labels: backport 12.4

#883 [TASK] #102440 - Merge EXT:t3editor into backend
  Documentation/CodeSnippets/CtrlTypeTypes.rst.txt
  Documentation/CodeSnippets/T3editor1.rst.txt
  Documentation/ColumnsConfig/Introduction/Index.rst
  Documentation/ColumnsConfig/Type/Text/Index.rst
  Documentation/ColumnsConfig/Type/Text/Properties/Format.rst
  Documentation/ColumnsConfig/Type/Text/Properties/Rows.rst
  Documentation/ColumnsConfig/Type/Text/T3Editor/Examples.rst
  Documentation/ColumnsConfig/Type/Text/T3Editor/Index.rst
  Documentation/Images/ManualScreenshots/Codeeditor.png
  Documentation/Images/Rst/T3editor1.rst.txt
  Documentation/Settings.cfg
  Documentation/codesnippets.php
  Documentation/screenshots.json
Labels: changelog

#886 Fix small typo
  Documentation/ColumnsConfig/CommonProperties/Mode.rst
Labels: backport 11.5, backport 12.4

#890 Add snippet in ext_localconf.php for custom FieldInformation
  Documentation/ColumnsConfig/CommonProperties/FieldInformation.rst
Labels: backport 11.5, backport 12.4

#893 Fix missing backtick
  Documentation/ColumnsConfig/Type/Select/Properties/ForeignTableWhere.rst
Labels: backport 11.5, backport 12.4

#896 [FEATURE] #102279 - Auto create DB fields from TCA for type "select"
  Documentation/ColumnsConfig/Type/Select/CheckBox/Properties.rst
  Documentation/ColumnsConfig/Type/Select/Index.rst
  Documentation/ColumnsConfig/Type/Select/MultipleSideBySide/Properties.rst
  Documentation/ColumnsConfig/Type/Select/Properties/DbFieldLength.rst
  Documentation/ColumnsConfig/Type/Select/Properties/Index.rst
  Documentation/ColumnsConfig/Type/Select/Single/Properties.rst
  Documentation/ColumnsConfig/Type/Select/SingleBox/Properties.rst
  Documentation/ColumnsConfig/Type/Select/Tree/Properties.rst
Labels: changelog
