Repository TYPO3-Documentation/TYPO3CMS-Reference-TCA, pull requests merged in 2023-11, with the labels that each got.

#843 Fix typos in ColumnsConfig>Type>Inline>Properties chapter
  Documentation/ColumnsConfig/Type/Inline/Properties/Appearance.rst
Labels: backport 12.4

#847 Refer to TSconfig config for richtextConfiguration
  Documentation/ColumnsConfig/Type/Text/Properties/RichtextConfiguration.rst
Labels: backport 11.5, backport 12.4

#846 [TASK] Add anchor to "Migration" section of TCA type "file"
  Documentation/ColumnsConfig/Type/File/Index.rst
Labels: backport 12.4

#851 Add missing quote in PHP code
  Documentation/ColumnsConfig/Type/Group/Index.rst
Labels: backport 11.5, backport 12.4

#856 Fix spelling of allowNonIdValues
  Documentation/ColumnsConfig/Type/Select/CheckBox/Properties.rst
  Documentation/ColumnsConfig/Type/Select/MultipleSideBySide/Properties.rst
  Documentation/ColumnsConfig/Type/Select/Single/Properties.rst
  Documentation/ColumnsConfig/Type/Select/SingleBox/Properties.rst
  Documentation/ColumnsConfig/Type/Select/Tree/Properties.rst
Labels: backport 11.5, backport 12.4

#861 Remove exclusiveKeys property for some select renderTypes
  Documentation/ColumnsConfig/Type/Select/CheckBox/Properties.rst
  Documentation/ColumnsConfig/Type/Select/Properties/ExclusiveKeys.rst
  Documentation/ColumnsConfig/Type/Select/Single/Properties.rst
  Documentation/ColumnsConfig/Type/Select/SingleBox/Properties.rst
Labels: backport 11.5, backport 12.4

#863 Remove duplicate label definition
  Documentation/ColumnsConfig/Type/Select/Single/Properties.rst
Labels: backport 11.5, backport 12.4

#869 Add itemGroup property to list of select properties
  Documentation/ColumnsConfig/Type/Select/CheckBox/Properties.rst
  Documentation/ColumnsConfig/Type/Select/MultipleSideBySide/Properties.rst
  Documentation/ColumnsConfig/Type/Select/Single/Properties.rst
  Documentation/ColumnsConfig/Type/Select/SingleBox/Properties.rst
  Documentation/ColumnsConfig/Type/Select/Tree/Properties.rst
Labels: backport 11.5, backport 12.4

#868 Change slug generatorOptions.fields examples
  Documentation/ColumnsConfig/Type/Slug/Properties/GeneratorOptions.rst
Labels: backport 11.5, backport 12.4

#870 Clarify foreign_table_where
  Documentation/ColumnsConfig/Type/Select/Properties/ForeignTableWhere.rst
Labels: backport 11.5, backport 12.4

#877 [FEATURE] #102210 - Auto-create DB fields from TCA columns for type "inline"
  Documentation/ColumnsConfig/Type/Inline/Index.rst
Labels: changelog

#878 [FEATURE] #102237 - Auto-create DB fields from TCA columns for type "number"
  Documentation/ColumnsConfig/Type/Number/Index.rst
Labels: changelog

#879 Remove required from Eval options
  Documentation/ColumnsConfig/Type/Input/Properties/Eval.rst
Labels: backport 11.5, backport 12.4
