Repository TYPO3-Documentation/TYPO3CMS-Reference-TCA, pull requests merged in 2023-08, with the labels that each got.

#750 [BUGFIX] Add value tag for checkbox FlexForm example
  Documentation/CodeSnippets/Manual/FlexformCheckbox2.rst.txt
Labels: backport 12.4

#755 [TASK] Streamline MM sections
  Documentation/ColumnsConfig/Type/Group/Properties/Mm.rst
  Documentation/ColumnsConfig/Type/Inline/Properties/Mm.rst
  Documentation/ColumnsConfig/Type/Select/Properties/Mm.rst
  Documentation/Settings.cfg
Labels: backport 11.5, backport 12.4

#758 [TASK] Streamline manual links
  Documentation/BestPractises/LanguageFields.rst
  Documentation/Ctrl/Properties/LanguageField.rst
  Documentation/Settings.cfg
Labels: backport 12.4

#759 [FEATURE] #95061 - Auto creation of MM tables from TCA
  Documentation/ColumnsConfig/Type/Group/Properties/Mm.rst
  Documentation/ColumnsConfig/Type/Inline/Properties/Mm.rst
  Documentation/ColumnsConfig/Type/Select/Properties/Mm.rst
Labels: changelog, backport 11.5, backport 12.4

#763 explain the popup window
  Documentation/ColumnsConfig/CommonProperties/FieldControl/EditPopup.rst
Labels: backport 11.5, backport 12.4
