Repository TYPO3-Documentation/TYPO3CMS-Reference-TCA, pull requests merged in 2023-06, with the labels that each got.

#707 correct extensionKey for system extension with example
  Documentation/ColumnsConfig/Type/User/Index.rst
Labels: backport-required

#709 Add important note about custom formengine elements
  Documentation/ColumnsConfig/Type/User/Index.rst
Labels: backport 11.5, backport 12.4

#715 [TASK] Resolve rendering warnings
  Documentation/ColumnsConfig/CommonProperties/Mm.rst
  Documentation/ColumnsConfig/CommonProperties/Search.rst
  Documentation/ColumnsConfig/Type/File/Properties/Appearance.rst
  Documentation/ColumnsConfig/Type/Group/Properties/Mm.rst
  Documentation/ColumnsConfig/Type/Select/Properties/ForeignTableWhere.rst
  Documentation/ColumnsConfig/Type/Select/Properties/Mm.rst
Labels: backport 12.4

#713 [TASK] Remove sentence about "cols" property in "none" type
  Documentation/ColumnsConfig/Type/None/Properties/Size.rst
Labels: backport 12.4

#714 [TASK] Adjust note in format property of datetime type
  Documentation/ColumnsConfig/Type/Datetime/Properties/Format.rst
Labels: backport 12.4

#712 [BUGFIX] Correct examples for $GLOBALS['TCA'][$table]['ctrl']['security']
  Documentation/Ctrl/Properties/Security.rst
Labels: backport 11.5, backport 12.4

#706 Update DisplayCond.rst
  Documentation/Columns/Properties/DisplayCond.rst
Labels: backport 12.4

#723 [BUGFIX] Correct introduction for TCA type "file"
  Documentation/ColumnsConfig/Type/File/Index.rst
Labels: backport 12.4

#726 Fix double "only" in AdminOnly.rst
  Documentation/Ctrl/Properties/AdminOnly.rst
Labels: backport 11.5, backport 12.4

#728 [TASK] Add note about outdated example for formattedLabel_userFunc
  Documentation/Ctrl/Properties/FormattedLabelUserFunc.rst
Labels: backport 12.4

#731 [TASK] #101082 - Remove deprecated file reference functionality
  Documentation/ColumnsConfig/Type/File/Properties/Appearance.rst
  Documentation/ColumnsConfig/Type/Group/Properties/Appearance.rst
  Documentation/ColumnsConfig/Type/Group/Properties/Index.rst
Labels: changelog

#722 [TASK] #101009 - Remove TCA config MM_insert_fields
  Documentation/ColumnsConfig/CommonProperties/Mm.rst
  Documentation/ColumnsConfig/Type/Group/Properties/Mm.rst
  Documentation/ColumnsConfig/Type/Select/Properties/Mm.rst
Labels: changelog

#735 [ISSUE] Sentence inside ColumnsConfig/Type/User/Index.rst is cut off …
  Documentation/ColumnsConfig/Type/User/Index.rst
Labels: backport 11.5, backport 12.4

#733 Follow naming conventions for tables on MM page
  Documentation/ColumnsConfig/Type/Group/Properties/Mm.rst
Labels: backport 11.5, backport 12.4
