Repository TYPO3-Documentation/TYPO3CMS-Reference-TCA, pull requests merged in 2023-10, with the labels that each got.

#807 Fix wrong reference to language file
  Documentation/ColumnsConfig/Type/ImageManipulation/Properties/CropVariants.rst
Labels: backport 11.5, backport 12.4

#804 [TASK] Add links on "text" TCA type page
  Documentation/ColumnsConfig/Type/Text/Index.rst
  Documentation/Settings.cfg
Labels: backport 11.5, backport 12.4

#803 [TASK] Add link to FlexForms description on FlexForm page
  Documentation/ColumnsConfig/Type/Flex/Index.rst
Labels: backport 11.5, backport 12.4

#798 [TASK] Move note about auto-generated slug db field
  Documentation/ColumnsConfig/Type/Slug/Examples.rst
  Documentation/ColumnsConfig/Type/Slug/Index.rst
Labels: backport 12.4

#796 [TASK] #102108 - Remove obscure TCA [types][bitmask_*] settings
  Documentation/Types/Properties/BitmaskExcludelistBits.rst
  Documentation/Types/Properties/BitmaskValueField.rst
  Documentation/Types/Properties/Index.rst
Labels: changelog

#806 [FEATURE] #102107 - Auto-create DB fields from TCA columns for type "color"
  Documentation/ColumnsConfig/Type/Color/Index.rst
Labels: changelog

#805 [FEATURE] #102106 - Auto-create DB fields from TCA columns for type "password"
  Documentation/ColumnsConfig/Type/Password/Index.rst
Labels: changelog

#802 [FEATURE] #101908 - Auto-create DB fields from TCA columns for type "group"
  Documentation/ColumnsConfig/Type/Group/Index.rst
Labels: changelog

#801 [FEATURE] #101915 - Auto-create DB fields from TCA columns for type "language"
  Documentation/ColumnsConfig/Type/Language/Index.rst
Labels: changelog

#800 [FEATURE] #101890 - Auto-create DB fields from TCA columns for type "imageManipulation"
  Documentation/ColumnsConfig/Type/ImageManipulation/Index.rst
Labels: changelog

#799 [FEATURE] #101890 - Auto-create DB fields from TCA columns for type "folder"
  Documentation/ColumnsConfig/Type/Folder/Index.rst
Labels: changelog

#797 [FEATURE] #101653 - Auto-create DB fields from TCA columns for type "check"
  Documentation/ColumnsConfig/Type/Check/Index.rst
Labels: changelog

#815 [FEATURE] #101986 - Auto-create DB fields from TCA columns for type "text"
  Documentation/ColumnsConfig/Type/Text/Index.rst
Labels: changelog

#816 [FEATURE] #101997 - Auto-create DB fields from TCA columns for type "flex"
  Documentation/ColumnsConfig/Type/Flex/Index.rst
Labels: changelog

#817 [FEATURE] #101654 - Auto-create DB fields from TCA columns for type "email"
  Documentation/ColumnsConfig/Type/Email/Index.rst
Labels: changelog

#818 [FEATURE] #101553 - Auto-create DB fields from TCA columns for type "file"
  Documentation/ColumnsConfig/Type/File/Index.rst
Labels: changelog

#819 [TASK] Add missing note about auto-created DB fields from TCA in v12
  Documentation/ColumnsConfig/Type/Category/Index.rst
  Documentation/ColumnsConfig/Type/Datetime/Index.rst
  Documentation/ColumnsConfig/Type/Uuid/Index.rst
Labels: changelog, backport 12.4

#820 [TASK] Add stub for new TCA type "json"
  Documentation/ColumnsConfig/Type/Json/Index.rst
Labels: changelog, backport 12.4

#824 [FEATURE] #102163 - Auto-create DB fields from TCA columns for type "link"
  Documentation/ColumnsConfig/Type/Link/Index.rst
Labels: changelog

#823 [FEATURE] #102163 - Auto-create DB fields from TCA columns for type "radio"
  Documentation/ColumnsConfig/Type/Radio/Index.rst
Labels: changelog

#826 [BUGFIX] Correct usage of :file: in MM section
  Documentation/ColumnsConfig/CommonProperties/Mm.rst
Labels: backport 11.5, backport 12.4

#830 [BUGFIX] Correct indentation for toctree in Select/Tree
  Documentation/ColumnsConfig/Type/Select/Tree/Index.rst
Labels: backport 11.5, backport 12.4

#834 [TASK] #101554 - Remove MM_hasUidField
  Documentation/ColumnsConfig/CommonProperties/Mm.rst
  Documentation/ColumnsConfig/CommonProperties/Multiple.rst
  Documentation/ColumnsConfig/Type/Group/Properties/Mm.rst
  Documentation/ColumnsConfig/Type/Inline/Properties/Mm.rst
  Documentation/ColumnsConfig/Type/Select/Properties/Mm.rst
Labels: changelog

#829 [FEATURE] #101843 - Allow configuration of color palettes
  Documentation/ColumnsConfig/Type/Color/Index.rst
Labels: changelog

#836 [TASK] #102224 - Remove TemplaVoila-related FlexForm dataStructure lookups
  Documentation/ColumnsConfig/Type/Flex/AboutDataStructures.rst
  Documentation/ColumnsConfig/Type/Flex/Properties/DsPointerFieldSearchParent.rst
  Documentation/ColumnsConfig/Type/Flex/Properties/DsPointerFieldSearchParentSubField.rst
  Documentation/ColumnsConfig/Type/Flex/Properties/DsTableField.rst
  Documentation/ColumnsConfig/Type/Flex/Properties/Index.rst
Labels: changelog

#837 [TASK] #102224 - Add note about removing FlexForm dataStructure lookups in v13
  Documentation/ColumnsConfig/Type/Flex/AboutDataStructures.rst
  Documentation/ColumnsConfig/Type/Flex/Properties/DsPointerFieldSearchParent.rst
  Documentation/ColumnsConfig/Type/Flex/Properties/DsPointerFieldSearchParentSubField.rst
  Documentation/ColumnsConfig/Type/Flex/Properties/DsTableField.rst
Labels: changelog

#833 [FEATURE] Add preview renderer
  Documentation/Ctrl/Properties/Index.rst
  Documentation/Ctrl/Properties/PreviewRenderer.rst
Labels: content missing, backport 11.5, backport 12.4
