Repository TYPO3-Documentation/TYPO3CMS-Reference-TCA, pull requests merged in 2024-09, with the labels that each got.

#1163 [TASK] Merge properties back into types page
  Documentation/Types/Examples.rst
  Documentation/Types/Index.rst
  Documentation/Types/Introduction.rst
  Documentation/Types/Properties/BitmaskExcludelistBits.rst
  Documentation/Types/Properties/BitmaskValueField.rst
  Documentation/Types/Properties/Index.rst
  Documentation/Types/Properties/Showitem.rst
  Documentation/Types/Properties/SubtypeValueField.rst
  Documentation/Types/Properties/SubtypesExcludelist.rst
  Documentation/Types/Properties/_creationOptions.php
  Documentation/Types/_CodeSnippets/_creationOptions.php
  Documentation/Types/_Examples/_10_ShowItem.rst.txt
  Documentation/Types/_Examples/_20_Subtypes.rst.txt
  Documentation/Types/_Examples/_30_RequiredType.rst.txt
  Documentation/Types/_Examples/_40_OptionalTypes.rst.txt
  Documentation/Types/_Examples/_50_ColumnsOverrides.rst.txt
  Documentation/Types/_Examples/_60_PreviewRenderer.rst.txt
  Documentation/Types/_Examples/_70_SaveAndClose.rst.txt
  Documentation/Types/_Properties/_ColumnsOverrides.rst.txt
  Documentation/Types/_Properties/_CreationOptions.rst.txt
  Documentation/Types/_Properties/_PreviewRenderer.rst.txt
  Documentation/Types/_Properties/_Showitem.rst.txt
  Documentation/Types/_Properties/_SubtypeValueField.rst.txt
  Documentation/Types/_Properties/_SubtypesAddlist.rst.txt
  Documentation/Types/_Properties/_SubtypesExcludelist.rst.txt
Labels: backport-required

#1168 [TASK] Display confvals as TCA in Search facets
  Documentation/guides.xml
Labels: backport 11.5, backport 12.4

#1171 [TASK] Merge properties back into interface page
  Documentation/Interface/Examples.rst
  Documentation/Interface/Index.rst
  Documentation/Interface/Properties.rst
  Documentation/Interface/_CodeSnippets/_interface.php
Labels: backport 12.4

#1173 [TASK] Merge properties back into columns page
  Documentation/Columns/DisplayConditions.rst
  Documentation/Columns/Examples.rst
  Documentation/Columns/Index.rst
  Documentation/Columns/Properties/Config.rst
  Documentation/Columns/Properties/DisplayCond.rst
  Documentation/Columns/Properties/Index.rst
  Documentation/Columns/_Properties/_Config.rst.txt
  Documentation/Columns/_Properties/_Description.rst.txt
  Documentation/Columns/_Properties/_DisplayCond.rst.txt
  Documentation/Columns/_Properties/_Exclude.rst.txt
  Documentation/Columns/_Properties/_L10nDisplay.rst.txt
  Documentation/Columns/_Properties/_L10nMode.rst.txt
  Documentation/Columns/_Properties/_Label.rst.txt
  Documentation/Columns/_Properties/_OnChange.rst.txt
Labels: backport 12.4

#1175 [TASK] Merge properties back into columns page
  Documentation/Palettes/Examples.rst
  Documentation/Palettes/Index.rst
  Documentation/Palettes/Properties/Index.rst
  Documentation/Palettes/_Properties/_Description.rst.txt
  Documentation/Palettes/_Properties/_IsHiddenPalette.rst.txt
  Documentation/Palettes/_Properties/_Label.rst.txt
  Documentation/Palettes/_Properties/_Showitem.rst.txt
Labels: backport 12.4

#1177 [BUGFIX] Avoid new paragraph in note for input's "max"
  Documentation/ColumnsConfig/Type/Input/_Properties/_Max.rst.txt
Labels: backport 12.4
