Repository TYPO3-Documentation/TYPO3CMS-Reference-TCA, pull requests merged in 2024-10, with the labels that each got.

#1179 [TASK] Use --minimal-test CLI option for documentation tests
  .github/workflows/test-documentation.yml
  Makefile
Labels: backport 11.5, backport 12.4

#1167 Prefer LinkFactory::createUri() for pure URI creation
  Documentation/ColumnsConfig/Type/Link/_Snippets/_SomeService.php
Labels: backport 12.4

#1187 [TASK] Remove TYPO3 v11.x version hints
  Documentation/ColumnsConfig/CommonProperties/ItemsProcFunc.rst
  Documentation/ColumnsConfig/CommonProperties/Mm.rst
  Documentation/ColumnsConfig/Type/Category/Examples.rst
  Documentation/ColumnsConfig/Type/Category/_Properties/_Mm.rst.txt
  Documentation/ColumnsConfig/Type/Check/_Properties/_ItemsProcFunc.rst.txt
  Documentation/ColumnsConfig/Type/Group/StoredDataValues.rst
  Documentation/ColumnsConfig/Type/Group/_Properties/_Mm.rst.txt
  Documentation/ColumnsConfig/Type/Inline/_Properties/_Mm.rst.txt
  Documentation/ColumnsConfig/Type/Radio/_Properties/_ItemsProcFunc.rst.txt
  Documentation/ColumnsConfig/Type/Select/CheckBox/_Properties/_ForeignTable.rst.txt
  Documentation/ColumnsConfig/Type/Select/CheckBox/_Properties/_Mm.rst.txt
  Documentation/ColumnsConfig/Type/Select/MultipleSideBySide/_Properties/_ForeignTable.rst.txt
  Documentation/ColumnsConfig/Type/Select/MultipleSideBySide/_Properties/_Mm.rst.txt
  Documentation/ColumnsConfig/Type/Select/Single/_Properties/_ForeignTable.rst.txt
  Documentation/ColumnsConfig/Type/Select/Single/_Properties/_Mm.rst.txt
  Documentation/ColumnsConfig/Type/Select/SingleBox/_Properties/_ForeignTable.rst.txt
  Documentation/ColumnsConfig/Type/Select/SingleBox/_Properties/_Mm.rst.txt
  Documentation/ColumnsConfig/Type/Select/Tree/_Properties/_ForeignTable.rst.txt
  Documentation/ColumnsConfig/Type/Select/Tree/_Properties/_Mm.rst.txt
  Documentation/Palettes/_Properties/_Description.rst.txt
Labels: backport 13.4
