Repository TYPO3-Documentation/TYPO3CMS-Reference-TCA, pull requests merged in 2024-01, with the labels that each got.

#899 Update allowed image types
  Documentation/ColumnsConfig/Type/File/Index.rst
Labels: backport-required

#900 [TASK] Remove outdated TCA type user dbType json
  Documentation/ColumnsConfig/Type/User/Index.rst
  Documentation/ColumnsConfig/Type/User/_includes/_FieldMapElement.php
Labels: backport 12.4

#904 [TASK] Remove old versionadded directives
  Documentation/ColumnsConfig/Type/Select/Properties/ItemGroups.rst
  Documentation/ColumnsConfig/Type/Select/Properties/SortItems.rst
Labels: backport 12.4

#905 [FEATURE] #95808 - Enable item groups for foreign_table for select type
  Documentation/ColumnsConfig/Type/Select/Properties/ForeignTableItemGroup.rst
  Documentation/ColumnsConfig/Type/Select/Properties/Index.rst
  Documentation/ColumnsConfig/Type/Select/Properties/ItemGroups.rst
Labels: changelog

#906 [BUGFIX] Add missing category properties around foreign_table
  Documentation/ColumnsConfig/Type/Category/Properties/ForeignTable.rst
  Documentation/ColumnsConfig/Type/Category/Properties/ForeignTablePrefix.rst
  Documentation/ColumnsConfig/Type/Category/Properties/ForeignTableWhere.rst
  Documentation/ColumnsConfig/Type/Category/Properties/Index.rst
  Documentation/ColumnsConfig/Type/Category/Properties/Mm.rst
  Documentation/ColumnsConfig/Type/Select/Properties/ForeignTablePrefix.rst
  Documentation/ColumnsConfig/Type/Select/Properties/ForeignTableWhere.rst
Labels: backport 11.5, backport 12.4

#913 Add example code to create URL from a link field
  Documentation/ColumnsConfig/Type/Link/Index.rst
Labels: backport 12.4

#912 Fix nullable example
  Documentation/ColumnsConfig/Type/Link/Index.rst
Labels: backport-required

#916 [TASK] Remove wrong default for type `file` `allowed`
  Documentation/ColumnsConfig/Type/File/Properties/Allowed.rst
Labels: backport 12.4

#910 [TASK] Add missing itemGroups property to category type
  Documentation/ColumnsConfig/Type/Category/Properties/ForeignTable.rst
  Documentation/ColumnsConfig/Type/Category/Properties/ForeignTablePrefix.rst
  Documentation/ColumnsConfig/Type/Category/Properties/Index.rst
  Documentation/ColumnsConfig/Type/Category/Properties/ItemGroups.rst
  Documentation/ColumnsConfig/Type/Select/Properties/ItemGroups.rst
Labels: backport 12.4

#920 Use admonition for "disableHideAtCopy" TSconfig hint
  Documentation/Ctrl/Properties/HideAtCopy.rst
Labels: backport 11.5, backport 12.4

#919 [TASK] Break up "page/userTSconfig" as two words
  Documentation/ColumnsConfig/CommonProperties/FieldWizard/OtherLanguageContent.rst
Labels: backport 11.5, backport 12.4

#923 [FEATURE] #95808 - Enable item groups for foreign_table for category type
  Documentation/ColumnsConfig/Type/Category/Properties/ForeignTableItemGroup.rst
  Documentation/ColumnsConfig/Type/Select/Properties/ForeignTableItemGroup.rst
Labels: changelog

#929 Update list of valid searchable field types
  Documentation/Ctrl/Properties/SearchFields.rst
Labels: backport 12.4
