Repository TYPO3-Documentation/TYPO3CMS-Reference-TCA, pull requests merged in 2024-08, with the labels that each got.

#1119 [TASK] Merge properties to none page
  Documentation/ColumnsConfig/Type/None/Examples.rst
  Documentation/ColumnsConfig/Type/None/Index.rst
  Documentation/ColumnsConfig/Type/None/Properties/Index.rst
  Documentation/ColumnsConfig/Type/None/_Properties/_FieldInformation.rst.txt
  Documentation/ColumnsConfig/Type/None/_Properties/_Format.rst.txt
  Documentation/ColumnsConfig/Type/None/_Properties/_PassContent.rst.txt
  Documentation/ColumnsConfig/Type/None/_Properties/_Size.rst.txt
  Documentation/ColumnsConfig/Type/None/_Properties/_cols_migration.diff
Labels: backport 12.4

#1120 [TASK] Merge properties to number page
  Documentation/ColumnsConfig/Type/Number/Index.rst
  Documentation/ColumnsConfig/Type/Number/Properties/Autocomplete.rst
  Documentation/ColumnsConfig/Type/Number/Properties/Index.rst
  Documentation/ColumnsConfig/Type/Number/Properties/Slider.rst
  Documentation/ColumnsConfig/Type/Number/_Properties/_AllowLanguageSynchronization.php
  Documentation/ColumnsConfig/Type/Number/_Properties/_AllowLanguageSynchronization.rst.txt
  Documentation/ColumnsConfig/Type/Number/_Properties/_Autocomplete.php
  Documentation/ColumnsConfig/Type/Number/_Properties/_Autocomplete.rst.txt
  Documentation/ColumnsConfig/Type/Number/_Properties/_Default.rst.txt
  Documentation/ColumnsConfig/Type/Number/_Properties/_FieldControl.rst.txt
  Documentation/ColumnsConfig/Type/Number/_Properties/_FieldInformation.rst.txt
  Documentation/ColumnsConfig/Type/Number/_Properties/_FieldWizard.rst.txt
  Documentation/ColumnsConfig/Type/Number/_Properties/_Format.rst.txt
  Documentation/ColumnsConfig/Type/Number/_Properties/_Mode.rst.txt
  Documentation/ColumnsConfig/Type/Number/_Properties/_Nullable.php
  Documentation/ColumnsConfig/Type/Number/_Properties/_Nullable.rst.txt
  Documentation/ColumnsConfig/Type/Number/_Properties/_PlaceHolder.php
  Documentation/ColumnsConfig/Type/Number/_Properties/_Range.php
  Documentation/ColumnsConfig/Type/Number/_Properties/_Range.rst.txt
  Documentation/ColumnsConfig/Type/Number/_Properties/_ReadOnly.rst.txt
  Documentation/ColumnsConfig/Type/Number/_Properties/_Required.rst.txt
  Documentation/ColumnsConfig/Type/Number/_Properties/_Size.rst.txt
  Documentation/ColumnsConfig/Type/Number/_Properties/_Slider.rst.txt
  Documentation/ColumnsConfig/Type/Number/_Properties/_SliderDecimal.php
  Documentation/ColumnsConfig/Type/Number/_Properties/_SliderLimited.php
  Documentation/ColumnsConfig/Type/Number/_Properties/_SliderUnlimited.php
  Documentation/ColumnsConfig/Type/Number/_Properties/_ValuePicker.php
  Documentation/ColumnsConfig/Type/Number/_Properties/_ValuePicker.rst.txt
  Documentation/ColumnsConfig/Type/Number/_Snippets/_migration_double.diff
  Documentation/ColumnsConfig/Type/Number/_Snippets/_migration_int.diff
Labels: backport 12.4

#1125 [TASK] Merge properties to radio page
  Documentation/ColumnsConfig/Type/Radio/Examples.rst
  Documentation/ColumnsConfig/Type/Radio/Index.rst
  Documentation/ColumnsConfig/Type/Radio/Properties/Index.rst
  Documentation/ColumnsConfig/Type/Radio/_Properties/_AllowLanguageSynchronization.rst.txt
  Documentation/ColumnsConfig/Type/Radio/_Properties/_Default.rst.txt
  Documentation/ColumnsConfig/Type/Radio/_Properties/_FieldControl.rst.txt
  Documentation/ColumnsConfig/Type/Radio/_Properties/_FieldInformation.rst.txt
  Documentation/ColumnsConfig/Type/Radio/_Properties/_FieldWizard.rst.txt
  Documentation/ColumnsConfig/Type/Radio/_Properties/_Items.rst.txt
  Documentation/ColumnsConfig/Type/Radio/_Properties/_ItemsProcFunc.rst.txt
  Documentation/ColumnsConfig/Type/Radio/_Properties/_ReadOnly.rst.txt
  Documentation/ColumnsConfig/Type/Radio/_Snippet/_AllowLanguageSynchronization.php
Labels: backport 12.4

#1128 [TASK] Merge properties to slug page
  Documentation/ColumnsConfig/Type/Uuid/Index.rst
  Documentation/ColumnsConfig/Type/Uuid/Properties/Index.rst
  Documentation/ColumnsConfig/Type/Uuid/_Properties/_EnableCopyToClipboard.rst.txt
  Documentation/ColumnsConfig/Type/Uuid/_Properties/_FieldInformation.rst.txt
  Documentation/ColumnsConfig/Type/Uuid/_Properties/_Required.rst.txt
  Documentation/ColumnsConfig/Type/Uuid/_Properties/_Size.rst.txt
  Documentation/ColumnsConfig/Type/Uuid/_Properties/_Version.rst.txt
  Documentation/ColumnsConfig/Type/Uuid/_Snippets/_basic.php
Labels: backport 12.4

#1130 [TASK] Merge properties to text - belayout page
  Documentation/ColumnsConfig/Type/Text/BeLayoutWizard/Examples.rst
  Documentation/ColumnsConfig/Type/Text/BeLayoutWizard/Index.rst
  Documentation/ColumnsConfig/Type/Text/BeLayoutWizard/Properties.rst
  Documentation/ColumnsConfig/Type/Text/BeLayoutWizard/_Properties/_Default.rst.txt
  Documentation/ColumnsConfig/Type/Text/BeLayoutWizard/_Properties/_FieldInformation.rst.txt
  Documentation/ColumnsConfig/Type/Text/BeLayoutWizard/_Properties/_FieldWizard.rst.txt
Labels: backport 12.4

#1132 [TASK] Merge properties to text - codeEditor page
  Documentation/ColumnsConfig/Type/Text/Properties/Format.rst
  Documentation/ColumnsConfig/Type/Text/T3Editor/Examples.rst
  Documentation/ColumnsConfig/Type/Text/T3Editor/Index.rst
  Documentation/ColumnsConfig/Type/Text/T3Editor/Properties.rst
  Documentation/ColumnsConfig/Type/Text/T3Editor/_Properties/_AllowLanguageSynchronization.rst.txt
  Documentation/ColumnsConfig/Type/Text/T3Editor/_Properties/_FieldControl.rst.txt
  Documentation/ColumnsConfig/Type/Text/T3Editor/_Properties/_FieldInformation.rst.txt
  Documentation/ColumnsConfig/Type/Text/T3Editor/_Properties/_FieldWizard.rst.txt
  Documentation/ColumnsConfig/Type/Text/T3Editor/_Properties/_Format.rst.txt
  Documentation/ColumnsConfig/Type/Text/T3Editor/_Properties/_ReadOnly.rst.txt
  Documentation/ColumnsConfig/Type/Text/T3Editor/_Properties/_Rows.rst.txt
  Documentation/ColumnsConfig/Type/Text/T3Editor/_Properties/_Search.rst.txt
  Documentation/ColumnsConfig/Type/Text/T3Editor/_Properties/_Softref.rst.txt
  Documentation/ColumnsConfig/Type/Text/T3Editor/_Snippets/_AllowLanguageSynchronization.php
  Documentation/ColumnsConfig/Type/Text/T3Editor/_Snippets/_Format.php
  Documentation/ColumnsConfig/Type/Text/T3Editor/_Snippets/_Search.php
  Documentation/ColumnsConfig/Type/Text/T3Editor/_Snippets/_migration.diff
Labels: backport-required

#1133 Update Index.rst, fixed spelling
  Documentation/BestPractises/Index.rst
Labels: backport 11.5, backport 12.4

#1136 [TASK] Merge properties to text - table page
  Documentation/ColumnsConfig/Type/Index.rst
  Documentation/ColumnsConfig/Type/Text/TextTable/Examples.rst
  Documentation/ColumnsConfig/Type/Text/TextTable/Index.rst
  Documentation/ColumnsConfig/Type/Text/TextTable/Properties.rst
  Documentation/ColumnsConfig/Type/Text/TextTable/_Properties/_AllowLanguageSynchronization.rst.txt
  Documentation/ColumnsConfig/Type/Text/TextTable/_Properties/_Default.rst.txt
  Documentation/ColumnsConfig/Type/Text/TextTable/_Properties/_EnableTabulator.rst.txt
  Documentation/ColumnsConfig/Type/Text/TextTable/_Properties/_FieldControl.rst.txt
  Documentation/ColumnsConfig/Type/Text/TextTable/_Properties/_FieldInformation.rst.txt
  Documentation/ColumnsConfig/Type/Text/TextTable/_Properties/_FieldWizard.rst.txt
  Documentation/ColumnsConfig/Type/Text/TextTable/_Properties/_FixedFont.rst.txt
  Documentation/ColumnsConfig/Type/Text/TextTable/_Properties/_IsIn.rst.txt
  Documentation/ColumnsConfig/Type/Text/TextTable/_Properties/_Max.rst.txt
  Documentation/ColumnsConfig/Type/Text/TextTable/_Properties/_Placeholder.rst.txt
  Documentation/ColumnsConfig/Type/Text/TextTable/_Properties/_ReadOnly.rst.txt
  Documentation/ColumnsConfig/Type/Text/TextTable/_Properties/_Rows.rst.txt
  Documentation/ColumnsConfig/Type/Text/TextTable/_Properties/_Search.rst.txt
  Documentation/ColumnsConfig/Type/Text/TextTable/_Properties/_Softref.rst.txt
  Documentation/ColumnsConfig/Type/Text/TextTable/_Properties/_Wrap.rst.txt
  Documentation/ColumnsConfig/Type/Text/TextTable/_Snippets/_AllowLanguageSynchronization.php
  Documentation/ColumnsConfig/Type/Text/TextTable/_Snippets/_Search.php
Labels: backport 12.4

#1140 [TASK] Merge properties to selectsinglebox
  Documentation/ColumnsConfig/Type/Select/Single/Index.rst
  Documentation/ColumnsConfig/Type/Select/Single/_Properties/_DbFieldLength.rst.txt
  Documentation/ColumnsConfig/Type/Select/Single/_Snippets/_DbFieldLength.php
  Documentation/ColumnsConfig/Type/Select/SingleBox/Examples.rst
  Documentation/ColumnsConfig/Type/Select/SingleBox/Index.rst
  Documentation/ColumnsConfig/Type/Select/SingleBox/Properties.rst
  Documentation/ColumnsConfig/Type/Select/SingleBox/_Properties/_AllowNonIdValues.rst.txt
  Documentation/ColumnsConfig/Type/Select/SingleBox/_Properties/_AuthMode.rst.txt
  Documentation/ColumnsConfig/Type/Select/SingleBox/_Properties/_AuthModeEnforce.rst.txt
  Documentation/ColumnsConfig/Type/Select/SingleBox/_Properties/_AutoSizeMax.rst.txt
  Documentation/ColumnsConfig/Type/Select/SingleBox/_Properties/_Behaviour.rst.txt
  Documentation/ColumnsConfig/Type/Select/SingleBox/_Properties/_DbFieldLength.rst.txt
  Documentation/ColumnsConfig/Type/Select/SingleBox/_Properties/_Default.rst.txt
  Documentation/ColumnsConfig/Type/Select/SingleBox/_Properties/_DisableNonMatchingValueElement.rst.txt
  Documentation/ColumnsConfig/Type/Select/SingleBox/_Properties/_FieldControl.rst.txt
  Documentation/ColumnsConfig/Type/Select/SingleBox/_Properties/_FieldInformation.rst.txt
  Documentation/ColumnsConfig/Type/Select/SingleBox/_Properties/_FieldWizard.rst.txt
  Documentation/ColumnsConfig/Type/Select/SingleBox/_Properties/_FileFolderConfig.rst.txt
  Documentation/ColumnsConfig/Type/Select/SingleBox/_Properties/_ForeignTable.rst.txt
  Documentation/ColumnsConfig/Type/Select/SingleBox/_Properties/_ForeignTablePrefix.rst.txt
  Documentation/ColumnsConfig/Type/Select/SingleBox/_Properties/_ForeignTableWhere.rst.txt
  Documentation/ColumnsConfig/Type/Select/SingleBox/_Properties/_ItemGroups.rst.txt
  Documentation/ColumnsConfig/Type/Select/SingleBox/_Properties/_Items.rst.txt
  Documentation/ColumnsConfig/Type/Select/SingleBox/_Properties/_ItemsProcFunc.rst.txt
  Documentation/ColumnsConfig/Type/Select/SingleBox/_Properties/_LocalizeReferencesAtParentLocalization.rst.txt
  Documentation/ColumnsConfig/Type/Select/SingleBox/_Properties/_Maxitems.rst.txt
  Documentation/ColumnsConfig/Type/Select/SingleBox/_Properties/_Minitems.rst.txt
  Documentation/ColumnsConfig/Type/Select/SingleBox/_Properties/_Mm.rst.txt
  Documentation/ColumnsConfig/Type/Select/SingleBox/_Properties/_Multiple.rst.txt
  Documentation/ColumnsConfig/Type/Select/SingleBox/_Properties/_ReadOnly.rst.txt
  Documentation/ColumnsConfig/Type/Select/SingleBox/_Properties/_Size.rst.txt
  Documentation/ColumnsConfig/Type/Select/SingleBox/_Snippets/_AllowLanguageSynchronization.php
  Documentation/ColumnsConfig/Type/Select/SingleBox/_Snippets/_DbFieldLength.php
Labels: backport 12.4

#1141 [TASK] Merge properties to selectTree
  Documentation/ColumnsConfig/Type/Select/Properties/SelectTreeConfig.rst
  Documentation/ColumnsConfig/Type/Select/Tree/Examples.rst
  Documentation/ColumnsConfig/Type/Select/Tree/Index.rst
  Documentation/ColumnsConfig/Type/Select/Tree/Properties.rst
  Documentation/ColumnsConfig/Type/Select/Tree/_Properties/_AllowNonIdValues.rst.txt
  Documentation/ColumnsConfig/Type/Select/Tree/_Properties/_AuthMode.rst.txt
  Documentation/ColumnsConfig/Type/Select/Tree/_Properties/_AuthModeEnforce.rst.txt
  Documentation/ColumnsConfig/Type/Select/Tree/_Properties/_Behaviour.rst.txt
  Documentation/ColumnsConfig/Type/Select/Tree/_Properties/_DbFieldLength.rst.txt
  Documentation/ColumnsConfig/Type/Select/Tree/_Properties/_Default.rst.txt
  Documentation/ColumnsConfig/Type/Select/Tree/_Properties/_DisableNonMatchingValueElement.rst.txt
  Documentation/ColumnsConfig/Type/Select/Tree/_Properties/_ExclusiveKeys.rst.txt
  Documentation/ColumnsConfig/Type/Select/Tree/_Properties/_FieldInformation.rst.txt
  Documentation/ColumnsConfig/Type/Select/Tree/_Properties/_FieldWizard.rst.txt
  Documentation/ColumnsConfig/Type/Select/Tree/_Properties/_FileFolderConfig.rst.txt
  Documentation/ColumnsConfig/Type/Select/Tree/_Properties/_ForeignTable.rst.txt
  Documentation/ColumnsConfig/Type/Select/Tree/_Properties/_ForeignTablePrefix.rst.txt
  Documentation/ColumnsConfig/Type/Select/Tree/_Properties/_ForeignTableWhere.rst.txt
  Documentation/ColumnsConfig/Type/Select/Tree/_Properties/_Items.rst.txt
  Documentation/ColumnsConfig/Type/Select/Tree/_Properties/_ItemsProcFunc.rst.txt
  Documentation/ColumnsConfig/Type/Select/Tree/_Properties/_Maxitems.rst.txt
  Documentation/ColumnsConfig/Type/Select/Tree/_Properties/_Minitems.rst.txt
  Documentation/ColumnsConfig/Type/Select/Tree/_Properties/_Mm.rst.txt
  Documentation/ColumnsConfig/Type/Select/Tree/_Properties/_Multiple.rst.txt
  Documentation/ColumnsConfig/Type/Select/Tree/_Properties/_ReadOnly.rst.txt
  Documentation/ColumnsConfig/Type/Select/Tree/_Properties/_Size.rst.txt
  Documentation/ColumnsConfig/Type/Select/Tree/_Properties/_TreeConfig.rst.txt
  Documentation/ColumnsConfig/Type/Select/Tree/_Snippets/_AllowLanguageSynchronization.php
  Documentation/ColumnsConfig/Type/Select/Tree/_Snippets/_DbFieldLength.php
Labels: backport 12.4

#1142 [TASK] Merge properties to selectCheckbox
  Documentation/ColumnsConfig/Type/Select/CheckBox/Examples.rst
  Documentation/ColumnsConfig/Type/Select/CheckBox/Index.rst
  Documentation/ColumnsConfig/Type/Select/CheckBox/Properties.rst
  Documentation/ColumnsConfig/Type/Select/CheckBox/_Properties/_AllowNonIdValues.rst.txt
  Documentation/ColumnsConfig/Type/Select/CheckBox/_Properties/_Appearance.rst.txt
  Documentation/ColumnsConfig/Type/Select/CheckBox/_Properties/_AuthMode.rst.txt
  Documentation/ColumnsConfig/Type/Select/CheckBox/_Properties/_AuthModeEnforce.rst.txt
  Documentation/ColumnsConfig/Type/Select/CheckBox/_Properties/_AutoSizeMax.rst.txt
  Documentation/ColumnsConfig/Type/Select/CheckBox/_Properties/_Behaviour.rst.txt
  Documentation/ColumnsConfig/Type/Select/CheckBox/_Properties/_DbFieldLength.rst.txt
  Documentation/ColumnsConfig/Type/Select/CheckBox/_Properties/_Default.rst.txt
  Documentation/ColumnsConfig/Type/Select/CheckBox/_Properties/_DisableNonMatchingValueElement.rst.txt
  Documentation/ColumnsConfig/Type/Select/CheckBox/_Properties/_DontRemapTablesOnCopy.rst.txt
  Documentation/ColumnsConfig/Type/Select/CheckBox/_Properties/_FieldInformation.rst.txt
  Documentation/ColumnsConfig/Type/Select/CheckBox/_Properties/_FieldWizard.rst.txt
  Documentation/ColumnsConfig/Type/Select/CheckBox/_Properties/_FileFolderConfig.rst.txt
  Documentation/ColumnsConfig/Type/Select/CheckBox/_Properties/_ForeignTable.rst.txt
  Documentation/ColumnsConfig/Type/Select/CheckBox/_Properties/_ForeignTablePrefix.rst.txt
  Documentation/ColumnsConfig/Type/Select/CheckBox/_Properties/_ForeignTableWhere.rst.txt
  Documentation/ColumnsConfig/Type/Select/CheckBox/_Properties/_ItemGroups.rst.txt
  Documentation/ColumnsConfig/Type/Select/CheckBox/_Properties/_Items.rst.txt
  Documentation/ColumnsConfig/Type/Select/CheckBox/_Properties/_ItemsProcFunc.rst.txt
  Documentation/ColumnsConfig/Type/Select/CheckBox/_Properties/_Maxitems.rst.txt
  Documentation/ColumnsConfig/Type/Select/CheckBox/_Properties/_Minitems.rst.txt
  Documentation/ColumnsConfig/Type/Select/CheckBox/_Properties/_Mm.rst.txt
  Documentation/ColumnsConfig/Type/Select/CheckBox/_Properties/_Multiple.rst.txt
  Documentation/ColumnsConfig/Type/Select/CheckBox/_Properties/_ReadOnly.rst.txt
  Documentation/ColumnsConfig/Type/Select/CheckBox/_Properties/_Size.rst.txt
  Documentation/ColumnsConfig/Type/Select/CheckBox/_Snippets/_AllowLanguageSynchronization.php
  Documentation/ColumnsConfig/Type/Select/CheckBox/_Snippets/_DbFieldLength.php
  Documentation/ColumnsConfig/Type/Select/Properties/CheckBoxAppearance.rst
  Documentation/ColumnsConfig/Type/Select/Properties/ItemGroups.rst
Labels: backport 12.4

#1144 [TASK] Follow up: Merge properties to select multiple side by side
  Documentation/ColumnsConfig/Type/Select/MultipleSideBySide/Index.rst
  Documentation/ColumnsConfig/Type/Select/MultipleSideBySide/_Properties/_FieldControl/_AddRecord.rst.txt
  Documentation/ColumnsConfig/Type/Select/MultipleSideBySide/_Properties/_FieldControl/_EditPopup.rst.txt
  Documentation/ColumnsConfig/Type/Select/MultipleSideBySide/_Properties/_FieldControl/_ResetSelection.rst.txt
  Documentation/ColumnsConfig/Type/Select/MultipleSideBySide/_Properties/_FieldWizard.rst.txt
  Documentation/ColumnsConfig/Type/Select/MultipleSideBySide/_Properties/_FileFolderConfig.rst.txt
  Documentation/ColumnsConfig/Type/Select/MultipleSideBySide/_Properties/_ForeignTable.rst.txt
  Documentation/ColumnsConfig/Type/Select/MultipleSideBySide/_Properties/_ForeignTablePrefix.rst.txt
  Documentation/ColumnsConfig/Type/Select/MultipleSideBySide/_Properties/_ForeignTableWhere.rst.txt
  Documentation/ColumnsConfig/Type/Select/MultipleSideBySide/_Properties/_Items.rst.txt
  Documentation/ColumnsConfig/Type/Select/MultipleSideBySide/_Properties/_Mm.rst.txt
  Documentation/ColumnsConfig/Type/Select/MultipleSideBySide/_Snippets/_AllowLanguageSynchronization.php
  Documentation/ColumnsConfig/Type/Select/MultipleSideBySide/_Snippets/_DbFieldLength.php
Labels: backport 12.4

#1147 [TASK] Remove common properties
  Documentation/ColumnsConfig/Type/Select/CheckBox/Index.rst
  Documentation/ColumnsConfig/Type/Select/CheckBox/_Properties/_ForeignTableItemGroup.rst.txt
  Documentation/ColumnsConfig/Type/Select/CheckBox/_Properties/_ForeignTablePrefix.rst.txt
  Documentation/ColumnsConfig/Type/Select/Index.rst
  Documentation/ColumnsConfig/Type/Select/MultipleSideBySide/Index.rst
  Documentation/ColumnsConfig/Type/Select/MultipleSideBySide/_Properties/_ExclusiveKeys.rst.txt
  Documentation/ColumnsConfig/Type/Select/MultipleSideBySide/_Properties/_MultiSelectFilterItems.rst.txt
  Documentation/ColumnsConfig/Type/Select/Properties/AllowNonIdValues.rst
  Documentation/ColumnsConfig/Type/Select/Properties/AuthMode.rst
  Documentation/ColumnsConfig/Type/Select/Properties/AuthModeEnforce.rst
  Documentation/ColumnsConfig/Type/Select/Properties/DbFieldLength.rst
  Documentation/ColumnsConfig/Type/Select/Properties/Default.rst
  Documentation/ColumnsConfig/Type/Select/Properties/DisableNonMatchingValueElement.rst
  Documentation/ColumnsConfig/Type/Select/Properties/ExclusiveKeys.rst
  Documentation/ColumnsConfig/Type/Select/Properties/FileFolderConfig.rst
  Documentation/ColumnsConfig/Type/Select/Properties/ForeignTable.rst
  Documentation/ColumnsConfig/Type/Select/Properties/ForeignTableItemGroup.rst
  Documentation/ColumnsConfig/Type/Select/Properties/ForeignTablePrefix.rst
  Documentation/ColumnsConfig/Type/Select/Properties/ForeignTableWhere.rst
  Documentation/ColumnsConfig/Type/Select/Properties/Index.rst
  Documentation/ColumnsConfig/Type/Select/Properties/ItemGroups.rst
  Documentation/ColumnsConfig/Type/Select/Properties/Items.rst
  Documentation/ColumnsConfig/Type/Select/Properties/Mm.rst
  Documentation/ColumnsConfig/Type/Select/Single/Index.rst
  Documentation/ColumnsConfig/Type/Select/Single/_Properties/_AllowNonIdValues.rst.txt
  Documentation/ColumnsConfig/Type/Select/Single/_Properties/_AuthMode.rst.txt
  Documentation/ColumnsConfig/Type/Select/Single/_Properties/_AuthModeEnforce.rst.txt
  Documentation/ColumnsConfig/Type/Select/Single/_Properties/_DbFieldLength.rst.txt
  Documentation/ColumnsConfig/Type/Select/Single/_Properties/_Default.rst.txt
  Documentation/ColumnsConfig/Type/Select/Single/_Properties/_DisableNonMatchingValueElement.rst.txt
  Documentation/ColumnsConfig/Type/Select/Single/_Properties/_FileFolderConfig.rst.txt
  Documentation/ColumnsConfig/Type/Select/Single/_Properties/_ForeignTable.rst.txt
  Documentation/ColumnsConfig/Type/Select/Single/_Properties/_ForeignTableItemGroup.rst.txt
  Documentation/ColumnsConfig/Type/Select/Single/_Properties/_ForeignTablePrefix.rst.txt
  Documentation/ColumnsConfig/Type/Select/Single/_Properties/_ForeignTableWhere.rst.txt
  Documentation/ColumnsConfig/Type/Select/Single/_Properties/_Items.rst.txt
  Documentation/ColumnsConfig/Type/Select/Single/_Properties/_Mm.rst.txt
  Documentation/ColumnsConfig/Type/Select/Single/_Properties/_SortItems.rst.txt
  Documentation/ColumnsConfig/Type/Select/Single/_Snippets/_ForeignFieldTableItemGroup.php
  Documentation/ColumnsConfig/Type/Select/SingleBox/Index.rst
  Documentation/ColumnsConfig/Type/Select/SingleBox/_Properties/_ForeignTableItemGroup.rst.txt
  Documentation/ColumnsConfig/Type/Select/Tree/Index.rst
  Documentation/ColumnsConfig/Type/Select/Tree/_Properties/_ForeignTableItemGroup.rst.txt
Labels: backport 12.4

#1148 [BUGFIX] Add missing labels
  Documentation/ColumnsConfig/Type/Select/Single/_Properties/_ItemsProcFunc.rst.txt
  Documentation/ColumnsConfig/Type/Text/T3Editor/Index.rst
Labels: backport 12.4

#1151 [TASK] Use glob for includes
  Documentation/ColumnsConfig/Type/Category/Index.rst
  Documentation/ColumnsConfig/Type/Check/Index.rst
  Documentation/ColumnsConfig/Type/Color/Index.rst
  Documentation/ColumnsConfig/Type/Datetime/Index.rst
  Documentation/ColumnsConfig/Type/Email/Index.rst
  Documentation/ColumnsConfig/Type/File/Index.rst
  Documentation/ColumnsConfig/Type/Flex/Index.rst
  Documentation/ColumnsConfig/Type/Folder/Index.rst
  Documentation/ColumnsConfig/Type/Group/Index.rst
  Documentation/ColumnsConfig/Type/Group/_Properties/_AllowLanguageSynchronization.rst.txt
  Documentation/ColumnsConfig/Type/Group/_Properties/_AutoSizeMax.rst.txt
  Documentation/ColumnsConfig/Type/Group/_Properties/_Default.rst.txt
  Documentation/ColumnsConfig/Type/Group/_Properties/_DontRemapTablesOnCopy.rst.txt
  Documentation/ColumnsConfig/Type/Group/_Properties/_FieldInformation.rst.txt
  Documentation/ColumnsConfig/Type/Group/_Properties/_LocalizeReferencesAtParentLocalization.rst.txt
  Documentation/ColumnsConfig/Type/Group/_Properties/_Maxitems.rst.txt
  Documentation/ColumnsConfig/Type/Group/_Properties/_Minitems.rst.txt
  Documentation/ColumnsConfig/Type/Group/_Properties/_Multiple.rst.txt
  Documentation/ColumnsConfig/Type/Group/_Properties/_ReadOnly.rst.txt
  Documentation/ColumnsConfig/Type/ImageManipulation/Index.rst
  Documentation/ColumnsConfig/Type/Inline/Index.rst
  Documentation/ColumnsConfig/Type/Inline/_Properties/_Behaviour.rst.txt
  Documentation/ColumnsConfig/Type/Inline/_Properties/_Maxitems.rst.txt
  Documentation/ColumnsConfig/Type/Inline/_Properties/_Minitems.rst.txt
  Documentation/ColumnsConfig/Type/Input/Index.rst
  Documentation/ColumnsConfig/Type/Json/Index.rst
  Documentation/ColumnsConfig/Type/Json/Properties.rst
  Documentation/ColumnsConfig/Type/Link/Index.rst
  Documentation/ColumnsConfig/Type/None/Index.rst
  Documentation/ColumnsConfig/Type/Number/Index.rst
  Documentation/ColumnsConfig/Type/Password/Index.rst
  Documentation/ColumnsConfig/Type/Radio/Index.rst
  Documentation/ColumnsConfig/Type/Select/MultipleSideBySide/Index.rst
  Documentation/ColumnsConfig/Type/Select/Single/Index.rst
  Documentation/ColumnsConfig/Type/Select/SingleBox/Index.rst
  Documentation/ColumnsConfig/Type/Select/Tree/Index.rst
  Documentation/ColumnsConfig/Type/Slug/Index.rst
  Documentation/ColumnsConfig/Type/Text/BeLayoutWizard/Index.rst
  Documentation/ColumnsConfig/Type/Text/Default/Index.rst
  Documentation/ColumnsConfig/Type/Text/T3Editor/Index.rst
  Documentation/ColumnsConfig/Type/Text/TextTable/Index.rst
  Documentation/ColumnsConfig/Type/Uuid/Index.rst
Labels: backport 12.4

#1152 [TASK] Rework workspace docs
  Documentation/Ctrl/Properties/VersioningWS.rst
  Documentation/Ctrl/Properties/VersioningWSAlwaysAllowLiveEdit.rst
Labels: backport 11.5, backport 12.4

#1156 [BUGFIX] Avoid autocompletion in TCA type password
  Documentation/ColumnsConfig/Type/Password/_Properties/_Autocomplete.rst.txt
Labels: backport 12.4

#1159 [TASK] Document `hideDeleteIcon` for TCA "Group fields"
  Documentation/ColumnsConfig/Type/Folder/_Properties/_HideDeleteIcon.rst.txt
  Documentation/ColumnsConfig/Type/Group/_Properties/_HideDeleteIcon.rst.txt
Labels: backport 12.4
