Repository TYPO3-Documentation/TYPO3CMS-Reference-TCA, pull requests merged in 2024-03, with the labels that each got.

#941 Remove references to t3ver_label which was removed in v10
  Documentation/Ctrl/Properties/VersioningWS.rst
Labels: backport 11.5, backport 12.4

#952 Fix typo in previous commit
  Documentation/Types/Properties/Showitem.rst
Labels: backport 11.5, backport 12.4

#964 [TASK] Switch codeblock to sql
  Documentation/Ctrl/Properties/VersioningWS.rst
Labels: backport 11.5, backport 12.4

#967 [BUGFIX] Fix references
  Documentation/ColumnsConfig/Type/File/Properties/Appearance.rst
  Documentation/ColumnsConfig/Type/Flex/Index.rst
  Documentation/ColumnsConfig/Type/Flex/Properties/DsPointerFieldSearchParent.rst
  Documentation/ColumnsConfig/Type/Flex/Properties/DsPointerFieldSearchParentSubField.rst
  Documentation/ColumnsConfig/Type/Flex/Properties/DsTableField.rst
  Documentation/ColumnsConfig/Type/Inline/Examples.rst
  Documentation/ColumnsConfig/Type/Password/Properties/PasswordPolicy.rst
  Documentation/ColumnsConfig/Type/Select/Properties/SelectTreeConfig.rst
Labels: backport 11.5, backport 12.4

#968 [DOCS] Switch to PHP based documentation rendering
  .github/workflows/test-documentation.yml
  Documentation/Includes.rst.txt
  Documentation/Index.rst
  Documentation/Settings.cfg
  Documentation/genindex.rst
  Documentation/guides.xml
  Documentation/screenshots.json
  Makefile
Labels: backport-required

#972 [TASK] Adjust .editorconfig for Makefile indentation
  .editorconfig
Labels: backport 11.5, backport 12.4

#976 change wording for Nullable TCA Config
  Documentation/ColumnsConfig/Type/Text/Properties/Nullable.rst
Labels: backport 12.4

#978 change wording for Nullable TCA Config
  Documentation/ColumnsConfig/Type/Color/Properties/Nullable.rst
  Documentation/ColumnsConfig/Type/Datetime/Properties/Nullable.rst
  Documentation/ColumnsConfig/Type/Email/Properties/Nullable.rst
  Documentation/ColumnsConfig/Type/Input/Properties/Nullable.rst
  Documentation/ColumnsConfig/Type/Link/Properties/Nullable.rst
  Documentation/ColumnsConfig/Type/Number/Properties/Nullable.rst
  Documentation/ColumnsConfig/Type/Password/Properties/Nullable.rst
Labels: backport 12.4

#987 [TASK] Overhaul types
  Documentation/Types/Examples.rst
  Documentation/Types/Index.rst
  Documentation/Types/Introduction.rst
  Documentation/Types/Properties/ColumnsOverrides.rst
  Documentation/Types/Properties/Showitem.rst
  Documentation/Types/Properties/SubtypeValueField.rst
  Documentation/Types/Properties/SubtypesAddlist.rst
  Documentation/Types/Properties/SubtypesExcludelist.rst
Labels: backport 11.5, backport 12.4

#986 [TASK] Overhaul palettes
  Documentation/Palettes/Examples.rst
  Documentation/Palettes/Index.rst
  Documentation/Palettes/Properties/Description.rst
  Documentation/Palettes/Properties/Index.rst
  Documentation/Palettes/Properties/IsHiddenPalette.rst
  Documentation/Palettes/Properties/Label.rst
  Documentation/Palettes/Properties/Showitem.rst
Labels: backport 11.5, backport 12.4

#992 [TASK] Overhaul fieldwizard and fieldcontroll
  Documentation/ColumnsConfig/CommonProperties/FieldControl/AddRecord.rst
  Documentation/ColumnsConfig/CommonProperties/FieldControl/EditPopup.rst
  Documentation/ColumnsConfig/CommonProperties/FieldControl/Index.rst
  Documentation/ColumnsConfig/CommonProperties/FieldControl/ListModule.rst
  Documentation/ColumnsConfig/CommonProperties/FieldControl/ResetSelection.rst
  Documentation/ColumnsConfig/CommonProperties/FieldWizard/DefaultLanguageDifferences.rst
  Documentation/ColumnsConfig/CommonProperties/FieldWizard/Index.rst
  Documentation/ColumnsConfig/CommonProperties/FieldWizard/LocalizationStateSelector.rst
  Documentation/ColumnsConfig/CommonProperties/FieldWizard/OtherLanguageContent.rst
  Documentation/ColumnsConfig/CommonProperties/FieldWizard/SelectIcons.rst
Labels: backport 11.5, backport 12.4

#998 [TASK] Overhaul color type
  Documentation/ColumnsConfig/Type/Color/Index.rst
  Documentation/ColumnsConfig/Type/Color/Properties/Index.rst
  Documentation/ColumnsConfig/Type/Color/Properties/Nullable.rst
  Documentation/ColumnsConfig/Type/Color/Properties/Size.rst
  Documentation/ColumnsConfig/Type/Color/Properties/ValuePicker.rst
Labels: backport 12.4

#1001 [TASK] Overhaul folder type
  Documentation/ColumnsConfig/Type/Folder/Index.rst
  Documentation/ColumnsConfig/Type/Folder/Properties/ElementBrowserEntryPoints.rst
  Documentation/ColumnsConfig/Type/Folder/Properties/FieldControl.rst
  Documentation/ColumnsConfig/Type/Folder/Properties/Index.rst
Labels: backport 12.4

#1002 [TASK] Overhaul group type
  Documentation/ColumnsConfig/Type/Group/Examples.rst
  Documentation/ColumnsConfig/Type/Group/Index.rst
  Documentation/ColumnsConfig/Type/Group/Properties/Allowed.rst
  Documentation/ColumnsConfig/Type/Group/Properties/ElementBrowserEntryPoints.rst
  Documentation/ColumnsConfig/Type/Group/Properties/FieldControl.rst
  Documentation/ColumnsConfig/Type/Group/Properties/FieldWizard.rst
  Documentation/ColumnsConfig/Type/Group/Properties/Filter.rst
  Documentation/ColumnsConfig/Type/Group/Properties/ForeignTable.rst
  Documentation/ColumnsConfig/Type/Group/Properties/HideSuggest.rst
  Documentation/ColumnsConfig/Type/Group/Properties/Index.rst
  Documentation/ColumnsConfig/Type/Group/Properties/Mm.rst
  Documentation/ColumnsConfig/Type/Group/Properties/PrependTname.rst
  Documentation/ColumnsConfig/Type/Group/Properties/SuggestOptions.rst
  Documentation/ColumnsConfig/Type/Group/StoredDataValues.rst
Labels: backport 11.5, backport 12.4

#1004 [TASK] Overhaul imagemanipulation type
  Documentation/ColumnsConfig/Type/ImageManipulation/Examples.rst
  Documentation/ColumnsConfig/Type/ImageManipulation/Index.rst
  Documentation/ColumnsConfig/Type/ImageManipulation/Properties/AllowedExtensions.rst
  Documentation/ColumnsConfig/Type/ImageManipulation/Properties/CropVariants.rst
  Documentation/ColumnsConfig/Type/ImageManipulation/Properties/FileField.rst
  Documentation/ColumnsConfig/Type/ImageManipulation/Properties/Index.rst
Labels: backport 11.5, backport 12.4

#1007 [TASK] Overhaul inline type
  Documentation/ColumnsConfig/Type/Inline/Examples.rst
  Documentation/ColumnsConfig/Type/Inline/Index.rst
  Documentation/ColumnsConfig/Type/Inline/Properties/Appearance.rst
  Documentation/ColumnsConfig/Type/Inline/Properties/BehaviourDisableMovingChildrenWithParent.rst
  Documentation/ColumnsConfig/Type/Inline/Properties/BehaviourEnableCascadingDelete.rst
  Documentation/ColumnsConfig/Type/Inline/Properties/CustomControls.rst
  Documentation/ColumnsConfig/Type/Inline/Properties/Filter.rst
  Documentation/ColumnsConfig/Type/Inline/Properties/ForeignDefaultSortby.rst
  Documentation/ColumnsConfig/Type/Inline/Properties/ForeignField.rst
  Documentation/ColumnsConfig/Type/Inline/Properties/ForeignLabel.rst
  Documentation/ColumnsConfig/Type/Inline/Properties/ForeignMatchFields.rst
  Documentation/ColumnsConfig/Type/Inline/Properties/ForeignSelector.rst
  Documentation/ColumnsConfig/Type/Inline/Properties/ForeignSortby.rst
  Documentation/ColumnsConfig/Type/Inline/Properties/ForeignTableField.rst
  Documentation/ColumnsConfig/Type/Inline/Properties/ForeignUnique.rst
  Documentation/ColumnsConfig/Type/Inline/Properties/Index.rst
  Documentation/ColumnsConfig/Type/Inline/Properties/Mm.rst
  Documentation/ColumnsConfig/Type/Inline/Properties/OverrideChildTCa.rst
  Documentation/ColumnsConfig/Type/Inline/Properties/Size.rst
  Documentation/ColumnsConfig/Type/Inline/Properties/SymmetricField.rst
  Documentation/ColumnsConfig/Type/Inline/Properties/SymmetricLabel.rst
  Documentation/ColumnsConfig/Type/Inline/Properties/SymmetricSortby.rst
Labels: backport 11.5, backport 12.4

#1009 [TASK] Overhaul json and language type
  Documentation/ColumnsConfig/Type/Json/Index.rst
  Documentation/ColumnsConfig/Type/Language/Examples.rst
  Documentation/ColumnsConfig/Type/Language/History.rst
  Documentation/ColumnsConfig/Type/Language/Index.rst
  Documentation/ColumnsConfig/Type/Language/Introduction.rst
  Documentation/ColumnsConfig/Type/Language/Migration.rst
  Documentation/ColumnsConfig/Type/Language/Properties/Index.rst
Labels: backport 12.4

#1010 [TASK] Overhaul link type
  Documentation/ColumnsConfig/Type/Link/Index.rst
  Documentation/ColumnsConfig/Type/Link/Properties/AllowedTypes.rst
  Documentation/ColumnsConfig/Type/Link/Properties/Appearance.rst
  Documentation/ColumnsConfig/Type/Link/Properties/Autocomplete.rst
  Documentation/ColumnsConfig/Type/Link/Properties/Index.rst
  Documentation/ColumnsConfig/Type/Link/Properties/Nullable.rst
  Documentation/ColumnsConfig/Type/Link/Properties/Size.rst
  Documentation/ColumnsConfig/Type/Link/Properties/ValuePicker.rst
Labels: backport 12.4

#1011 [TASK] Overhaul none type
  Documentation/ColumnsConfig/Type/None/Examples.rst
  Documentation/ColumnsConfig/Type/None/Index.rst
  Documentation/ColumnsConfig/Type/None/Properties/Format.rst
  Documentation/ColumnsConfig/Type/None/Properties/Index.rst
  Documentation/ColumnsConfig/Type/None/Properties/PassContent.rst
  Documentation/ColumnsConfig/Type/None/Properties/Size.rst
Labels: backport 11.5, backport 12.4

#1012 [TASK] Overhaul number type
  Documentation/ColumnsConfig/Type/Number/Index.rst
  Documentation/ColumnsConfig/Type/Number/Properties/Autocomplete.rst
  Documentation/ColumnsConfig/Type/Number/Properties/Format.rst
  Documentation/ColumnsConfig/Type/Number/Properties/Index.rst
  Documentation/ColumnsConfig/Type/Number/Properties/Nullable.rst
  Documentation/ColumnsConfig/Type/Number/Properties/Range.rst
  Documentation/ColumnsConfig/Type/Number/Properties/Size.rst
  Documentation/ColumnsConfig/Type/Number/Properties/Slider.rst
  Documentation/ColumnsConfig/Type/Number/Properties/ValuePicker.rst
Labels: backport 12.4

#1008 [TASK] Overhaul input type
  Documentation/ColumnsConfig/Type/Input/Index.rst
  Documentation/ColumnsConfig/Type/Input/Properties/Autocomplete.rst
  Documentation/ColumnsConfig/Type/Input/Properties/Eval.rst
  Documentation/ColumnsConfig/Type/Input/Properties/Index.rst
  Documentation/ColumnsConfig/Type/Input/Properties/IsIn.rst
  Documentation/ColumnsConfig/Type/Input/Properties/Max.rst
  Documentation/ColumnsConfig/Type/Input/Properties/Min.rst
  Documentation/ColumnsConfig/Type/Input/Properties/Nullable.rst
  Documentation/ColumnsConfig/Type/Input/Properties/Size.rst
  Documentation/ColumnsConfig/Type/Input/Properties/ValuePicker.rst
Labels: backport 11.5, backport 12.4

#1016 [TASK] Overhaul password type
  Documentation/ColumnsConfig/Type/Password/Index.rst
  Documentation/ColumnsConfig/Type/Password/Properties/Autocomplete.rst
  Documentation/ColumnsConfig/Type/Password/Properties/Hashed.rst
  Documentation/ColumnsConfig/Type/Password/Properties/Index.rst
  Documentation/ColumnsConfig/Type/Password/Properties/Nullable.rst
  Documentation/ColumnsConfig/Type/Password/Properties/PasswordGenerator.rst
  Documentation/ColumnsConfig/Type/Password/Properties/PasswordPolicy.rst
  Documentation/ColumnsConfig/Type/Password/Properties/Size.rst
Labels: backport 12.4

#1024 [TASK] Overhaul user type
  Documentation/ColumnsConfig/Type/User/Index.rst
Labels: backport 11.5, backport 12.4

#1021 [TASK] Overhaul select type
  Documentation/ColumnsConfig/Type/Select/CheckBox/DifferenceSelectCheckbox.rst
  Documentation/ColumnsConfig/Type/Select/CheckBox/Examples.rst
  Documentation/ColumnsConfig/Type/Select/CheckBox/Index.rst
  Documentation/ColumnsConfig/Type/Select/CheckBox/Properties.rst
  Documentation/ColumnsConfig/Type/Select/Index.rst
  Documentation/ColumnsConfig/Type/Select/MultipleSideBySide/Examples.rst
  Documentation/ColumnsConfig/Type/Select/MultipleSideBySide/Index.rst
  Documentation/ColumnsConfig/Type/Select/MultipleSideBySide/Properties.rst
  Documentation/ColumnsConfig/Type/Select/Properties/AllowNonIdValues.rst
  Documentation/ColumnsConfig/Type/Select/Properties/AuthMode.rst
  Documentation/ColumnsConfig/Type/Select/Properties/AuthModeEnforce.rst
  Documentation/ColumnsConfig/Type/Select/Properties/CheckBoxAppearance.rst
  Documentation/ColumnsConfig/Type/Select/Properties/DbFieldLength.rst
  Documentation/ColumnsConfig/Type/Select/Properties/Default.rst
  Documentation/ColumnsConfig/Type/Select/Properties/DisableNonMatchingValueElement.rst
  Documentation/ColumnsConfig/Type/Select/Properties/ExclusiveKeys.rst
  Documentation/ColumnsConfig/Type/Select/Properties/FileFolderConfig.rst
  Documentation/ColumnsConfig/Type/Select/Properties/ForeignTable.rst
  Documentation/ColumnsConfig/Type/Select/Properties/ForeignTableItemGroup.rst
  Documentation/ColumnsConfig/Type/Select/Properties/ForeignTablePrefix.rst
  Documentation/ColumnsConfig/Type/Select/Properties/ForeignTableWhere.rst
  Documentation/ColumnsConfig/Type/Select/Properties/Index.rst
  Documentation/ColumnsConfig/Type/Select/Properties/ItemGroups.rst
  Documentation/ColumnsConfig/Type/Select/Properties/Items.rst
  Documentation/ColumnsConfig/Type/Select/Properties/Mm.rst
  Documentation/ColumnsConfig/Type/Select/Properties/MultiSelectFilterItems.rst
  Documentation/ColumnsConfig/Type/Select/Properties/SelectTreeConfig.rst
  Documentation/ColumnsConfig/Type/Select/Properties/SortItems.rst
  Documentation/ColumnsConfig/Type/Select/Single/Examples.rst
  Documentation/ColumnsConfig/Type/Select/Single/Index.rst
  Documentation/ColumnsConfig/Type/Select/Single/Properties.rst
  Documentation/ColumnsConfig/Type/Select/SingleBox/Examples.rst
  Documentation/ColumnsConfig/Type/Select/SingleBox/Index.rst
  Documentation/ColumnsConfig/Type/Select/SingleBox/Properties.rst
  Documentation/ColumnsConfig/Type/Select/Tree/Examples.rst
  Documentation/ColumnsConfig/Type/Select/Tree/Index.rst
  Documentation/ColumnsConfig/Type/Select/Tree/Properties.rst
Labels: backport 11.5, backport 12.4

#1023 [TASK] Overhaul text type
  Documentation/ColumnsConfig/Type/Text/BeLayoutWizard/Examples.rst
  Documentation/ColumnsConfig/Type/Text/BeLayoutWizard/Index.rst
  Documentation/ColumnsConfig/Type/Text/BeLayoutWizard/Properties.rst
  Documentation/ColumnsConfig/Type/Text/Default/Examples.rst
  Documentation/ColumnsConfig/Type/Text/Default/Index.rst
  Documentation/ColumnsConfig/Type/Text/Default/Properties.rst
  Documentation/ColumnsConfig/Type/Text/Properties/Cols.rst
  Documentation/ColumnsConfig/Type/Text/Properties/EnableRichtext.rst
  Documentation/ColumnsConfig/Type/Text/Properties/EnableTabulator.rst
  Documentation/ColumnsConfig/Type/Text/Properties/Eval.rst
  Documentation/ColumnsConfig/Type/Text/Properties/FixedFont.rst
  Documentation/ColumnsConfig/Type/Text/Properties/Format.rst
  Documentation/ColumnsConfig/Type/Text/Properties/Index.rst
  Documentation/ColumnsConfig/Type/Text/Properties/IsIn.rst
  Documentation/ColumnsConfig/Type/Text/Properties/Max.rst
  Documentation/ColumnsConfig/Type/Text/Properties/Min.rst
  Documentation/ColumnsConfig/Type/Text/Properties/Nullable.rst
  Documentation/ColumnsConfig/Type/Text/Properties/RichtextConfiguration.rst
  Documentation/ColumnsConfig/Type/Text/Properties/Rows.rst
  Documentation/ColumnsConfig/Type/Text/Properties/Wrap.rst
  Documentation/ColumnsConfig/Type/Text/T3Editor/Properties.rst
  Documentation/ColumnsConfig/Type/Text/TextTable/Examples.rst
  Documentation/ColumnsConfig/Type/Text/TextTable/Index.rst
  Documentation/ColumnsConfig/Type/Text/TextTable/Properties.rst
Labels: backport 11.5, backport 12.4

#1026 [TASK] Overhaul common pages indentation
  Documentation/BestPractises/CommonFields.rst
  Documentation/BestPractises/Index.rst
  Documentation/BestPractises/LanguageFields.rst
  Documentation/Index.rst
  Documentation/Introduction/Index.rst
  Documentation/Sitemap.rst
Labels: backport 11.5, backport 12.4
